packages:
  - '.'

allowBuilds:
  '@prisma/engines': true
  esbuild: set this to true or false
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true

onlyBuiltDependencies:
  - esbuild
  - prisma
  - '@prisma/engines'
